apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  # this tells the aggregator how to verify that your API server is
  # actually who it claims to be
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNE1ETXhOREl5TURBMU5Gb1hEVEk0TURNeE1USXlNREExTkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSzFyCk9mUVUzQkpweUxFVEwwY1ovNU1hSDJ2VDZJZTBKbXFUekVkdEEvaDlrS1ExckFBKzV4U3gzTU0zN3JYUXdJU2cKVHpkRFJyZENKOVlJTEFQMkR4ME1uTXJTbEpFL3FGV3RwdGVNaWpqYndEVFlDNC9HbmZMWEJDd2szMkZJaDRiTgp3RXRuR1owdytmM2xIM0lTNXlvbEVtSXNPSjR3b1FXNHU1dHlDWXEzTDJ2emdXaVRaNFhRbVpxNG9ISlg5U0xkCnJaVzVINGNZdHU3K20yL0lWUDRFaXpKUkFkeGo1WHBiWC9LaXhOblpTRkh2QlFDTVdCRS9jMEtNRTd1dDkySzIKYTErUnh5VGR2eTNtZXFoQW1OQ3kva20yeVFCRVU4S0U4M3lMOUp2TVUvNGlmOTZmQ2xsdTdMbFJRNHl6eDlhbQpLODE0UXFOYVcxQ3NHSWgzYkJjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIdFNMeW1URFlScVF0Szl1Z2VDWjFXSUxCSjUKSGp5eXppeG0zc0JTallYMzB0R2hmU2F4SE5acHVCb1NURlZ3RjdrSDcrWEhVc2w0VjBrM3o4Uy9xdHlxYnZzeQpVU0tUaE13L1R6Tjdwbmtld3RsN0gzNUVCZHNlNXpUTE1PWEZvZ3JWQlpwSS9VTlVXMUFlZ2t3WXdjMDVVYVBMCjduL0VwR2habkhDdkhxR2M0TXpPMnBkTENXVW1BWXdabEFuREVpRmxWN21wWTRRNFZlR0J0VG9SMVM2bTdxWHEKT3A0WWkvVHB4eWpKaTQ0TXh0bUpNbjZPa2g2NGxhekl1WXZPSDY3Nk1GTTdYYThFbDFQaHJjbFlMWDFVdms1Wgp3OTcyaEtURVU2UmVxalYvUHdsQ1JwdHhtdk9MZzRWWGFxaStYTkNZZlVUazZaTnkva3Y2S0s2UFB1ND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo= 
  # these specify which group and version you're registering the API
  # server for
  group: custom.metrics.k8s.io
  version: v1beta1
  # these control how the aggregator prioritizes your registration.
  # it's not particularly relevant in this case.
  groupPriorityMinimum: 1000
  versionPriority: 10
  # finally, this points the aggregator at the service for your
  # API server that you created
  service:
    name: prometheus
    namespace: prom
