apiVersion: batch/v1
kind: Job
metadata:
  name: job3
spec:
  completions: 2
  #parallelism: 5
  #backoffLimit: 4
  #activeDeadlineSeconds: 20
  template:
    metadata:
      annotations:
        slo: "0.5"
        controller: "job3"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep", "30"]
      restartPolicy: Never
